name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy on VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          password: ${{ secrets.VM_PASSWORD }}
          port: 22
          script: |
            (
              flock -w 300 200 || { echo "Could not acquire deployment lock after waiting. Exiting."; exit 1; }

              echo "Stopping pm2 process (if running)..."
              if pm2 describe gdg-community-kit > /dev/null 2>&1; then
                pm2 stop gdg-community-kit
              fi

              # Change to the deployment directory
              cd /var/www/gdg-community-kit || { echo "Deployment directory not found"; exit 1; }

              echo "Creating a temporary deployment directory..."
              TEMP_DIR=$(mktemp -d)

              echo "Cloning repository to the temporary directory..."
              git clone git@github.com:praveentcom/gdg-community-kit.git "$TEMP_DIR"

              echo "Installing dependencies in the temporary directory..."
              cd "$TEMP_DIR"
              npm install

              echo "Building the application in the temporary directory..."
              npm run build

              echo "Switching to the new build..."
              cd /var/www/gdg-community-kit
              rsync -a --delete --exclude=node_modules --exclude=.env "$TEMP_DIR"/ /var/www/gdg-community-kit/

              echo "Cleaning up temporary directory..."
              rm -rf "$TEMP_DIR"

              echo "Starting (or restarting) pm2 process..."
              if pm2 describe gdg-community-kit > /dev/null 2>&1; then
                pm2 restart gdg-community-kit
              else
                pm2 start npm --name "gdg-community-kit" -- run start
                pm2 save
              fi
            ) 200>/tmp/deploy-gdg-community-kit.lock
