name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy on VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          password: ${{ secrets.VM_PASSWORD }}
          port: 22
          script: |
            (
              flock -w 300 200 || { echo "Could not acquire deployment lock after waiting. Exiting."; exit 1; }

              echo "Stopping pm2 process (if running)..."
              if pm2 describe gdg > /dev/null 2>&1; then
                pm2 stop gdg
              fi

              # Change to the deployment directory
              cd /var/www/gdg || { echo "Deployment directory not found"; exit 1; }
              
              echo "Deleting existing files except node_modules and .env..."
              find . -maxdepth 1 -mindepth 1 ! -name "node_modules" ! -name ".env" -exec rm -rf {} +

              # Add GitHub to known_hosts
              echo "Adding GitHub to known_hosts..."
              ssh-keyscan -H github.com >> ~/.ssh/known_hosts

              echo "Cloning repository to a temporary folder..."
              git clone git@github.com:praveentcom/gdg-community-kit.git /tmp/gdg-community-kit

              echo "Copying new files from the repository..."
              cp -r /tmp/gdg-community-kit/. .

              echo "Cleaning up temporary repository..."
              rm -rf /tmp/gdg-community-kit

              echo "Installing dependencies..."
              npm install

              echo "Building the application..."
              npm run build

              echo "Starting (or restarting) pm2 process..."
              if pm2 describe gdg > /dev/null 2>&1; then
                pm2 restart gdg
              else
                pm2 start npm --name "gdg" -- run start
              fi
            ) 200>/tmp/deploy-gdg.lock